// export const ARTIST_DETAILS_REQUEST = 'ARTIST_DETAILS_REQUEST';
// export const ARTIST_DETAILS_SUCCESS = 'ARTIST_DETAILS_SUCCESS';
// export const ARTIST_DETAILS_FAIL = 'ARTIST_DETAILS_FAIL';

// export const ARTIST_LIST_REQUEST = 'ARTIST_LIST_REQUEST';
// export const ARTIST_LIST_SUCCESS = 'ARTIST_LIST_SUCCESS';
// export const ARTIST_LIST_FAIL = 'ARTIST_LIST_FAIL';
// export const ARTIST_LIST_RESET = 'ARTIST_LIST_RESET';

export const ARTIST_ARTWORKS_REQUEST = 'ARTIST_ARTWORKS_REQUEST';
export const ARTIST_ARTWORKS_SUCCESS = 'ARTIST_ARTWORKS_SUCCESS';
export const ARTIST_ARTWORKS_FAIL = 'ARTIST_ARTWORKS_FAIL';
export const ARTIST_ARTWORKS_RESET = 'ARTIST_ARTWORKS_RESET';
