export const CART_CREATE_REQUEST = 'CART_CREATE_REQUEST';
export const CART_CREATE_SUCCESS = 'CART_CREATE_SUCCESS';
export const CART_CREATE_FAIL = 'CART_CREATE_FAIL';

export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS';

export const CART_REMOVE_ITEMS = 'CART_REMOVE_ITEMS';

export const CHANGE_CART_STEP = 'CHANGE_CART_STEP';

export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD';
